import React, { type CSSProperties } from 'react';

export type LegalDocStyles = {
    baseText: CSSProperties;
    h2: CSSProperties;
    h3: CSSProperties;
    ul: CSSProperties;
    li: CSSProperties;
    hr: CSSProperties;
    callout: CSSProperties;
};

/**
 * Renders the FULL OPWALLET Terms of Use + FULL .btc Domain Terms.
 * This component is intentionally "text only" so you can drop it into your modal scroll area.
 */
export function TermsText({
                              effectiveDate,
                              styles,
                          }: {
    effectiveDate: string;
    styles: LegalDocStyles;
}) {
    return (
        <>
            {/* =========================
                OPWALLET — TERMS OF USE
               ========================= */}

            <div style={{ marginBottom: 10 }}>
                <div style={{ ...styles.h2, fontSize: 14, marginTop: 2 }}>OPWALLET TERMS OF USE</div>
                <p style={{ ...styles.baseText, marginTop: 6, color: 'rgba(255,255,255,0.70)' }}>
                    ORANGE PILL LABS HOLDING LTD
                    <br />
                    Effective Date: {effectiveDate}
                </p>
            </div>

            <div style={styles.callout}>
                <strong>IMPORTANT NOTICE:</strong> THIS AGREEMENT CONTAINS A BINDING ARBITRATION PROVISION AND CLASS ACTION WAIVER IN
                ARTICLE 12. PLEASE READ THIS AGREEMENT CAREFULLY AS IT AFFECTS YOUR LEGAL RIGHTS.
            </div>

            <h2 style={styles.h2}>PREAMBLE</h2>
            <p style={styles.baseText}>
                ORANGE PILL LABS HOLDING LTD, a company incorporated in Abu Dhabi Global Market, United Arab Emirates ("OPNET,"
                "Company," "we," "us," or "our"), develops and publishes OPWALLET, a non-custodial cryptocurrency wallet browser
                extension enabling users to manage digital assets on the Bitcoin blockchain and the OPNet consensus layer. These Terms
                of Use ("Terms," "Terms of Use," or "Agreement") contain the terms and conditions governing your access to and use of
                the OPWALLET browser extension, associated websites, and all related services (collectively, the "Wallet" or
                "Software").
            </p>
            <p style={styles.baseText}>
                By installing, accessing, or using the Wallet, by clicking a button or checkbox to accept these Terms, or by taking
                any action that indicates acceptance, you (1) accept and agree to be bound by these Terms and all policies incorporated
                by reference, and (2) consent to the collection, use, and disclosure of information as described herein. If you do not
                agree to these Terms, you must not install, access, or use the Wallet. You represent that you are legally able to enter
                into contracts in your jurisdiction. If you are entering into this Agreement on behalf of an entity, you represent that
                you have authority to bind that entity to these Terms.
            </p>
            <p style={styles.baseText}>
                You represent and warrant that you and your financial institutions, or any party that owns or controls you or your
                financial institutions, are (1) not subject to sanctions or otherwise designated on any list of prohibited or
                restricted parties, including lists maintained by the United Nations Security Council, the United States Government, the
                European Union or its Member States, the United Arab Emirates, or other applicable government authority, and (2) not
                located in any country subject to comprehensive sanctions programs implemented by any of the foregoing jurisdictions.
            </p>

            <h2 style={styles.h2}>ARTICLE 1: DEFINITIONS</h2>
            <p style={styles.baseText}>
                In these Terms: "Bitcoin" means the decentralised peer-to-peer electronic cash system operating on the Bitcoin
                blockchain. "BTC" means the native cryptocurrency of the Bitcoin network. "OPNet" means the trustless, permissionless
                consensus layer enabling smart contract execution directly on Bitcoin Layer 1. "OP20 Token" means a fungible token
                standard deployed on the OPNet consensus layer. "OP721 Token" or "NFT" means a non-fungible token standard deployed on
                the OPNet consensus layer. ".btc Domain" means a human-readable identifier registered on the Bitcoin blockchain within
                the .btc namespace. "Private Key" means a cryptographic key that controls access to digital assets and enables
                transaction signing. "Seed Phrase" or "Recovery Phrase" means a series of words generated by the Wallet that can be
                used to recover Private Keys. "Smart Contract" means self-executing code deployed on OPNet. "Third-Party Service" means
                any product, service, or content provided by parties other than OPNET. "Your Content" means any data or content you
                submit through the Wallet.
            </p>

            <h2 style={styles.h2}>ARTICLE 2: THE WALLET AND ITS FUNCTIONALITY</h2>

            <h3 style={styles.h3}>2.1 Wallet Functionality</h3>
            <p style={styles.baseText}>
                OPWALLET is a browser extension that provides the following functionality: generation and management of cryptographic
                key pairs for Bitcoin and OPNet addresses, storage of Private Keys locally on your device in encrypted form, signing and
                broadcasting of Bitcoin transactions, management and transfer of BTC and OP20 Tokens, management and transfer of OP721
                Tokens (NFTs), registration and management of .btc Domains, resolution and navigation to .btc Domain addresses, and
                interaction with decentralised applications and Smart Contracts on OPNet. The Wallet is provided as a tool to facilitate
                your direct interaction with the Bitcoin blockchain and OPNet consensus layer.
            </p>

            <h3 style={styles.h3}>2.2 Non-Custodial Architecture</h3>
            <p style={styles.baseText}>
                <strong>THE WALLET IS ENTIRELY NON-CUSTODIAL.</strong> OPNET DOES NOT STORE, HAVE ACCESS TO, OR MAINTAIN CUSTODY OF YOUR
                PRIVATE KEYS, SEED PHRASES, PASSWORDS, OR ANY DIGITAL ASSETS. YOUR PRIVATE KEYS ARE GENERATED LOCALLY ON YOUR DEVICE AND
                STORED ONLY ON YOUR DEVICE IN ENCRYPTED FORM. OPNET CANNOT ACCESS YOUR PRIVATE KEYS, CANNOT RECOVER YOUR PRIVATE KEYS IF
                LOST, CANNOT REVERSE OR MODIFY ANY TRANSACTION YOU EXECUTE, CANNOT FREEZE OR SEIZE YOUR ASSETS, AND CANNOT RECOVER
                ASSETS SENT TO INCORRECT ADDRESSES. YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR THE SECURITY AND BACKUP OF YOUR
                PRIVATE KEYS AND SEED PHRASES.
            </p>

            <h3 style={styles.h3}>2.3 OPNet Consensus Layer</h3>
            <p style={styles.baseText}>
                The Wallet enables interaction with OPNet, a consensus layer that reads Bitcoin transactions and executes Smart Contract
                logic. OPNet operates directly on Bitcoin Layer 1 without introducing a separate gas token; all transactions use native
                BTC for fees. You must understand a critical characteristic: OPNet can revert Smart Contract execution if contract logic
                fails, but OPNet cannot reverse Bitcoin transfers that have already been broadcast. Once you send BTC in a Bitcoin
                transaction, that transfer is governed by Bitcoin's consensus rules and is irreversible regardless of whether the
                corresponding OPNet execution succeeds or fails. This creates the possibility of partial transaction reversion where you
                send BTC but do not receive expected tokens or other consideration.
            </p>

            <h3 style={styles.h3}>2.4 .btc Domain Functionality</h3>
            <p style={styles.baseText}>
                The Wallet provides functionality for registering, managing, and resolving .btc Domains. Domain registrations occur
                directly on the Bitcoin blockchain through transactions you broadcast; OPNET does not intermediate registrations. Once
                confirmed on Bitcoin, domain registrations are immutable and OPNET cannot modify, revoke, or transfer them. However,
                OPNET reserves the absolute right to block any .btc Domain from resolution through the Wallet at any time, for any
                reason, without notice. Blocking prevents the domain from resolving through OPNET services but does not affect on-chain
                ownership. Grounds for blocking include but are not limited to trademark infringement, illegal content, fraud, or any
                other reason OPNET deems appropriate. Separate .btc Domain Terms of Service may apply and are incorporated by reference.
            </p>

            <h3 style={styles.h3}>2.5 Integration with Third-Party Services</h3>
            <p style={styles.baseText}>
                The Wallet integrates with MotoSwap for token swapping functionality. When you execute swaps through the Wallet, you
                interact directly with MotoSwap Smart Contracts. Your use of MotoSwap is governed by the MotoSwap Terms of Service, which
                are separate from and in addition to these Terms. OPNET does not control MotoSwap Smart Contracts and is not responsible
                for swap execution, pricing, slippage, failed transactions, or any losses arising from swap functionality. The Wallet
                may also enable interaction with other decentralised applications and Smart Contracts deployed on OPNet. OPNET does not
                control, audit, endorse, or guarantee any third-party Smart Contract or decentralised application.
            </p>

            <h2 style={styles.h2}>ARTICLE 3: YOUR RESPONSIBILITIES</h2>

            <h3 style={styles.h3}>3.1 Key Security</h3>
            <p style={styles.baseText}>
                YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR MAINTAINING THE SECURITY AND CONFIDENTIALITY OF YOUR PRIVATE KEYS, SEED
                PHRASES, AND PASSWORDS. YOU MUST RECORD YOUR SEED PHRASE SECURELY AND MAINTAIN BACKUP COPIES IN SECURE LOCATIONS. YOU
                MUST NOT SHARE YOUR PRIVATE KEYS, SEED PHRASES, OR PASSWORDS WITH ANY PERSON OR ENTITY. OPNET WILL NEVER ASK FOR YOUR
                PRIVATE KEYS OR SEED PHRASES. ANYONE WHO OBTAINS YOUR PRIVATE KEYS OR SEED PHRASES CAN ACCESS AND TRANSFER ALL ASSETS IN
                YOUR WALLET. LOSS OF YOUR PRIVATE KEYS OR SEED PHRASES WILL RESULT IN PERMANENT, IRRECOVERABLE LOSS OF ALL ASSOCIATED
                ASSETS. OPNET HAS NO ABILITY TO RECOVER LOST KEYS OR PHRASES.
            </p>

            <h3 style={styles.h3}>3.2 Transaction Verification</h3>
            <p style={styles.baseText}>
                You are solely responsible for verifying all transaction details before signing and broadcasting. This includes verifying
                recipient addresses, token amounts, fee amounts, and Smart Contract interactions. Blockchain transactions are irreversible
                once broadcast and confirmed. OPNET cannot reverse, cancel, or modify any transaction you execute. Sending assets to
                incorrect addresses, interacting with malicious Smart Contracts, or approving fraudulent transactions will result in
                permanent loss that OPNET cannot recover.
            </p>

            <h3 style={styles.h3}>3.3 Software Updates</h3>
            <p style={styles.baseText}>
                You are responsible for keeping the Wallet software updated. We may release updates that contain security patches, bug
                fixes, or protocol compatibility changes. Failure to update may result in degraded functionality, security
                vulnerabilities, or incompatibility with network upgrades. OPNET is not responsible for any losses arising from your
                failure to maintain updated software.
            </p>

            <h3 style={styles.h3}>3.4 Compliance with Law</h3>
            <p style={styles.baseText}>
                You are solely responsible for compliance with all applicable laws, regulations, and rules in your jurisdiction. The
                legal status of cryptocurrency, digital assets, and blockchain technology varies by jurisdiction. You must independently
                determine whether your use of the Wallet complies with applicable law. OPNET does not provide legal, tax, or regulatory
                advice.
            </p>

            <h3 style={styles.h3}>3.5 Account Security for Third-Party Services</h3>
            <p style={styles.baseText}>
                To the extent you create accounts with Third-Party Services accessed through the Wallet, you are responsible for all
                activities occurring under those accounts. OPNET is not responsible for unauthorised access to third-party accounts,
                including access resulting from fraud, phishing, or other criminal activity.
            </p>

            <h2 style={styles.h2}>ARTICLE 4: THIRD-PARTY CONTENT AND SERVICES</h2>

            <h3 style={styles.h3}>4.1 Price Data</h3>
            <p style={styles.baseText}>
                The Wallet displays USD pricing information sourced from CoinGecko and potentially other third-party data providers. This
                pricing data is provided for informational convenience only. OPNET does not guarantee the accuracy, completeness,
                timeliness, or reliability of any price data. Price data may be delayed, inaccurate, or manipulated. Displayed prices may
                not reflect actual executable prices. You must not rely on displayed price data for trading decisions, financial planning,
                or any other purpose. OPNET disclaims all liability for decisions made based on displayed price data.
            </p>

            <h3 style={styles.h3}>4.2 Third-Party Smart Contracts and Tokens</h3>
            <p style={styles.baseText}>
                The Wallet enables interaction with Smart Contracts and tokens created by third parties. OPNET does not create, control,
                audit, endorse, or verify any third-party Smart Contract or token. Third-party tokens may be fraudulent, worthless, or
                designed to steal assets. Smart Contracts may contain bugs, vulnerabilities, or malicious code. Interacting with
                third-party Smart Contracts may result in total loss of assets. The appearance of a token in the Wallet does not
                constitute endorsement. You are solely responsible for evaluating the risks of any Smart Contract or token interaction.
            </p>

            <h3 style={styles.h3}>4.3 Third-Party Websites and Services</h3>
            <p style={styles.baseText}>
                The Wallet may contain links to or integrations with third-party websites and services. OPNET does not control and is not
                responsible for the content, privacy policies, terms of service, or practices of any third-party website or service. Your
                interactions with third-party services are governed by those services' terms and policies. OPNET disclaims all liability
                arising from your use of third-party services.
            </p>

            <h3 style={styles.h3}>4.4 Analytics</h3>
            <p style={styles.baseText}>
                The Wallet uses Google Analytics and potentially other analytics services to collect usage data. Analytics data may include
                device information, browser type, usage patterns, and other technical information. Analytics data is used to improve the
                Wallet and understand user behaviour. By using the Wallet, you consent to the collection of analytics data. You may
                disable certain analytics through browser settings, though this may affect functionality.
            </p>

            <h2 style={styles.h2}>ARTICLE 5: PROHIBITED USES</h2>
            <p style={styles.baseText}>
                You agree not to use the Wallet to: violate any applicable law, regulation, or rule; engage in money laundering, terrorist
                financing, or sanctions evasion; facilitate fraud, phishing, or other deceptive practices; distribute malware or malicious
                code; infringe intellectual property rights of any party; engage in market manipulation or wash trading; circumvent
                security measures or access controls; interfere with the operation of the Wallet or related systems; reverse engineer,
                decompile, or disassemble the Wallet except as permitted by law; use the Wallet in any manner that could damage, disable,
                or impair OPNET systems; or assist any third party in any of the foregoing activities.
            </p>

            <h2 style={styles.h2}>ARTICLE 6: CHANGES</h2>
            <h3 style={styles.h3}>6.1 Changes to the Wallet</h3>
            <p style={styles.baseText}>
                We may change, update, or discontinue any or all functionality of the Wallet at any time. We will use commercially
                reasonable efforts to communicate material changes through the Wallet interface, our website, or public communication
                channels. Some changes may be required to maintain compatibility with Bitcoin network upgrades, OPNet protocol changes,
                or browser updates. We are not liable for any modification, suspension, or discontinuation of the Wallet or any
                functionality thereof.
            </p>
            <h3 style={styles.h3}>6.2 Changes to These Terms</h3>
            <p style={styles.baseText}>
                We may modify these Terms at any time by posting updated Terms on our website or through the Wallet. For material changes
                that significantly affect your rights, we will provide thirty (30) days advance notice. Your continued use of the Wallet
                after the effective date of any modification constitutes acceptance of the modified Terms. If you do not agree to modified
                Terms, you must cease using the Wallet before the effective date.
            </p>

            <h2 style={styles.h2}>ARTICLE 7: PROPRIETARY RIGHTS</h2>
            <h3 style={styles.h3}>7.1 OPNET Intellectual Property</h3>
            <p style={styles.baseText}>
                We and our licensors own all right, title, and interest in the Wallet, including all intellectual property rights. Subject
                to these Terms, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to use the
                Wallet solely for your personal, non-commercial use in accordance with these Terms. You obtain no ownership rights in the
                Wallet. All rights not expressly granted are reserved.
            </p>
            <h3 style={styles.h3}>7.2 Restrictions</h3>
            <p style={styles.baseText}>
                You may not: modify, adapt, translate, or create derivative works of the Wallet; reverse engineer, disassemble, decompile,
                or otherwise attempt to derive source code except as permitted by applicable law; remove, alter, or obscure any proprietary
                notices; use the Wallet for any commercial purpose without our written consent; sublicense, sell, rent, lease, or transfer
                the Wallet; use our trademarks, logos, or branding without our written consent; or misrepresent your relationship with
                OPNET.
            </p>
            <h3 style={styles.h3}>7.3 Feedback</h3>
            <p style={styles.baseText}>
                If you provide suggestions, ideas, or feedback regarding the Wallet, you grant us a perpetual, irrevocable, worldwide,
                royalty-free license to use, modify, and incorporate such feedback without any obligation to you.
            </p>

            <h2 style={styles.h2}>ARTICLE 8: DISCLAIMERS</h2>
            <h3 style={styles.h3}>8.1 No Warranties</h3>
            <p style={styles.baseText}>
                THE WALLET IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR
                OTHERWISE. TO THE FULLEST EXTENT PERMITTED BY LAW, OPNET DISCLAIMS ALL WARRANTIES INCLUDING IMPLIED WARRANTIES OF
                MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND QUIET ENJOYMENT. OPNET DOES NOT WARRANT
                THAT THE WALLET WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE FROM VIRUSES OR HARMFUL COMPONENTS. OPNET DOES NOT
                WARRANT THAT ANY DEFECTS WILL BE CORRECTED. OPNET DOES NOT WARRANT THE ACCURACY OF ANY INFORMATION PROVIDED THROUGH THE
                WALLET.
            </p>
            <h3 style={styles.h3}>8.2 Blockchain and Cryptographic Risks</h3>
            <p style={styles.baseText}>
                THE WALLET RELIES ON BLOCKCHAIN TECHNOLOGY AND CRYPTOGRAPHIC SYSTEMS THAT PRESENT INHERENT RISKS. YOU ACKNOWLEDGE AND
                ACCEPT: BLOCKCHAIN TRANSACTIONS ARE IRREVERSIBLE AND OPNET CANNOT REVERSE OR MODIFY ANY TRANSACTION; PRIVATE KEY LOSS
                RESULTS IN PERMANENT ASSET LOSS; SMART CONTRACTS MAY CONTAIN BUGS OR VULNERABILITIES RESULTING IN ASSET LOSS; OPNET
                EXECUTIONS MAY FAIL WHILE BITCOIN TRANSFERS SUCCEED, RESULTING IN PARTIAL TRANSACTION REVERSION; DIGITAL ASSET VALUES ARE
                VOLATILE AND MAY DECLINE TO ZERO; NETWORK CONGESTION MAY DELAY OR PREVENT TRANSACTION CONFIRMATION; PROTOCOL UPGRADES MAY
                AFFECT WALLET FUNCTIONALITY; REGULATORY CHANGES MAY AFFECT THE LEGALITY OR AVAILABILITY OF SERVICES; AND CYBERSECURITY
                THREATS MAY COMPROMISE YOUR DEVICE OR THE WALLET.
            </p>
            <h3 style={styles.h3}>8.3 No Financial Advice</h3>
            <p style={styles.baseText}>
                OPNET DOES NOT PROVIDE FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE. NOTHING IN THE WALLET OR THESE TERMS CONSTITUTES A
                RECOMMENDATION TO BUY, SELL, OR HOLD ANY DIGITAL ASSET. PRICE DATA DISPLAYED IN THE WALLET IS FOR INFORMATIONAL PURPOSES
                ONLY AND MUST NOT BE RELIED UPON FOR TRADING DECISIONS. YOU ARE SOLELY RESPONSIBLE FOR YOUR FINANCIAL DECISIONS.
            </p>
            <h3 style={styles.h3}>8.4 Third-Party Disclaimer</h3>
            <p style={styles.baseText}>
                OPNET DOES NOT CONTROL AND IS NOT RESPONSIBLE FOR ANY THIRD-PARTY SERVICE, SMART CONTRACT, TOKEN, DECENTRALISED
                APPLICATION, OR CONTENT ACCESSED THROUGH THE WALLET. OPNET MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THIRD-PARTY
                SERVICES. YOUR USE OF THIRD-PARTY SERVICES IS AT YOUR SOLE RISK.
            </p>

            <h2 style={styles.h2}>ARTICLE 9: LIMITATION OF LIABILITY</h2>
            <h3 style={styles.h3}>9.1 Exclusion of Damages</h3>
            <p style={styles.baseText}>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL OPNET OR ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS,
                AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY
                DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, REVENUE, GOODWILL, DATA, DIGITAL ASSETS, USE, OR OTHER INTANGIBLE LOSSES,
                ARISING FROM OR RELATED TO THESE TERMS OR THE WALLET, REGARDLESS OF THE THEORY OF LIABILITY AND REGARDLESS OF WHETHER
                OPNET WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS EXCLUSION APPLIES TO: LOSS OF DIGITAL ASSETS DUE TO PRIVATE KEY
                LOSS OR COMPROMISE; LOSS OF DIGITAL ASSETS DUE TO TRANSACTION ERRORS OR INCORRECT ADDRESSES; LOSS OF DIGITAL ASSETS DUE TO
                SMART CONTRACT BUGS OR EXPLOITS; LOSS OF DIGITAL ASSETS DUE TO PARTIAL TRANSACTION REVERSION; LOSS OF VALUE DUE TO MARKET
                FLUCTUATIONS; INABILITY TO ACCESS THE WALLET OR YOUR ASSETS; UNAUTHORISED ACCESS TO YOUR WALLET OR ACCOUNTS; ACTIONS OF
                THIRD PARTIES; AND ANY OTHER LOSSES ARISING FROM YOUR USE OF THE WALLET.
            </p>
            <h3 style={styles.h3}>9.2 Maximum Liability</h3>
            <p style={styles.baseText}>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, OPNET'S TOTAL AGGREGATE LIABILITY ARISING FROM OR RELATED TO THESE TERMS OR THE
                WALLET SHALL NOT EXCEED ONE HUNDRED UNITED STATES DOLLARS (USD 100.00). THIS LIMITATION APPLIES REGARDLESS OF THE NUMBER
                OF CLAIMS AND REGARDLESS OF WHETHER OPNET HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <h3 style={styles.h3}>9.3 Essential Basis</h3>
            <p style={styles.baseText}>
                You acknowledge that the disclaimers and limitations in these Terms reflect a reasonable allocation of risk, form an
                essential basis of the bargain between you and OPNET, and that OPNET would not provide the Wallet without these
                limitations.
            </p>
            <h3 style={styles.h3}>9.4 Jurisdictional Limitations</h3>
            <p style={styles.baseText}>
                Some jurisdictions do not allow exclusion of certain warranties or limitation of certain damages. In such jurisdictions,
                OPNET's liability shall be limited to the fullest extent permitted by applicable law.
            </p>

            <h2 style={styles.h2}>ARTICLE 10: INDEMNIFICATION</h2>
            <p style={styles.baseText}>
                You agree to indemnify, defend, and hold harmless OPNET and its directors, officers, employees, agents, affiliates,
                successors, and assigns from and against any claims, damages, losses, liabilities, costs, and expenses (including
                reasonable legal fees) arising from or related to: your use of the Wallet; your violation of these Terms; your violation
                of any applicable law or third-party rights; your negligence or misconduct; your transactions or interactions with third
                parties; any content you submit through the Wallet; and any dispute between you and any third party. OPNET reserves the
                right to assume exclusive defence and control of any matter subject to indemnification by you, and you agree to cooperate
                with our defence.
            </p>

            <h2 style={styles.h2}>ARTICLE 11: TERMINATION</h2>
            <h3 style={styles.h3}>11.1 Termination by You</h3>
            <p style={styles.baseText}>
                You may terminate this Agreement at any time by uninstalling the Wallet and ceasing all use. Termination does not affect
                any transactions already broadcast to the blockchain or any assets stored in addresses associated with your Private Keys.
            </p>
            <h3 style={styles.h3}>11.2 Termination by OPNET</h3>
            <p style={styles.baseText}>
                We may terminate or suspend your access to the Wallet at any time, for any reason, with or without cause, with or without
                notice. Grounds for termination include but are not limited to: violation of these Terms; violation of applicable law;
                conduct harmful to OPNET or third parties; discontinuation of the Wallet; or any other reason in our sole discretion.
            </p>
            <h3 style={styles.h3}>11.3 Effect of Termination</h3>
            <p style={styles.baseText}>
                Upon termination: your license to use the Wallet immediately terminates; you must cease all use of the Wallet; your
                Private Keys and Seed Phrases remain under your control and can be used with compatible wallet software; your assets
                remain in your blockchain addresses and are not affected by termination; and Articles 7 through 13 and any other
                provisions that by their nature should survive termination shall survive.
            </p>

            <h2 style={styles.h2}>ARTICLE 12: DISPUTE RESOLUTION AND ARBITRATION</h2>
            <div style={styles.callout}>
                <strong>PLEASE READ THIS SECTION CAREFULLY.</strong> IT AFFECTS YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT
                IN COURT.
            </div>

            <h3 style={styles.h3}>12.1 Governing Law</h3>
            <p style={styles.baseText}>
                These Terms and any dispute arising from or related to these Terms or the Wallet shall be governed by and construed in
                accordance with the laws of Abu Dhabi Global Market, United Arab Emirates, and, to the extent applicable, the federal
                laws of the United Arab Emirates, without regard to conflict of laws principles.
            </p>

            <h3 style={styles.h3}>12.2 Binding Arbitration</h3>
            <p style={styles.baseText}>
                Any dispute, claim, or controversy arising from or related to these Terms or the Wallet shall be resolved by binding
                arbitration rather than in court, except that you may assert claims in small claims court if your claims qualify. The
                arbitration shall be conducted under the rules of the Abu Dhabi Commercial Conciliation and Arbitration Centre, or such
                other arbitral institution as the parties may agree. The seat of arbitration shall be Abu Dhabi. The language of
                arbitration shall be English. The arbitrator's decision shall be final, binding, and non-appealable. Judgment upon the
                award may be entered in any court having jurisdiction.
            </p>

            <h3 style={styles.h3}>12.3 Class Action Waiver</h3>
            <p style={styles.baseText}>
                YOU AND OPNET AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A
                PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, OR REPRESENTATIVE PROCEEDING. YOU AND OPNET EXPRESSLY WAIVE
                ANY RIGHT TO FILE OR PARTICIPATE IN A CLASS ACTION OR SEEK RELIEF ON A CLASS BASIS. Unless both you and OPNET agree, no
                arbitrator or judge may consolidate more than one person's claims or otherwise preside over any form of representative or
                class proceeding.
            </p>

            <h3 style={styles.h3}>12.4 Jury Trial Waiver</h3>
            <p style={styles.baseText}>
                TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AND OPNET EACH WAIVE ANY RIGHT TO A JURY TRIAL IN ANY PROCEEDING ARISING FROM
                OR RELATED TO THESE TERMS OR THE WALLET.
            </p>

            <h3 style={styles.h3}>12.5 International Users</h3>
            <p style={styles.baseText}>
                The Wallet is operated from the United Arab Emirates. If you access the Wallet from outside the United Arab Emirates, you
                do so at your own risk and are solely responsible for compliance with all applicable local, national, and international
                laws. The legal status of cryptocurrency wallets, digital assets, and blockchain technology varies by jurisdiction. OPNET
                makes no representation that the Wallet is appropriate, lawful, or available in any particular jurisdiction.
            </p>

            <h3 style={styles.h3}>12.6 Pre-Litigation Contact</h3>
            <p style={styles.baseText}>
                If any governmental authority, regulatory body, or law enforcement agency has concerns regarding the Wallet or wishes to
                take enforcement action, OPNET respectfully requests contact at report@opnet.org prior to initiating formal legal
                proceedings. OPNET commits to good-faith cooperation with legitimate regulatory inquiries and will take appropriate action
                to address valid concerns, including restricting access from affected jurisdictions if required by law.
            </p>

            <h2 style={styles.h2}>ARTICLE 13: GENERAL PROVISIONS</h2>
            <h3 style={styles.h3}>13.1 Entire Agreement</h3>
            <p style={styles.baseText}>
                These Terms, together with any documents incorporated by reference, constitute the entire agreement between you and OPNET
                regarding the Wallet and supersede all prior agreements and communications.
            </p>

            <h3 style={styles.h3}>13.2 Severability</h3>
            <p style={styles.baseText}>
                If any provision of these Terms is held invalid or unenforceable, such provision shall be modified to the minimum extent
                necessary to make it valid and enforceable, or if modification is not possible, shall be severed, and the remaining
                provisions shall continue in full force and effect.
            </p>

            <h3 style={styles.h3}>13.3 No Waiver</h3>
            <p style={styles.baseText}>
                No failure or delay by OPNET in exercising any right shall constitute a waiver of that right. Any waiver must be in
                writing and signed by OPNET.
            </p>

            <h3 style={styles.h3}>13.4 Assignment</h3>
            <p style={styles.baseText}>
                You may not assign these Terms without OPNET's prior written consent. OPNET may assign these Terms without notice in
                connection with a merger, acquisition, sale of assets, or corporate reorganisation, or to any affiliate. Subject to the
                foregoing, these Terms shall bind and inure to the benefit of the parties and their permitted successors and assigns.
            </p>

            <h3 style={styles.h3}>13.5 Force Majeure</h3>
            <p style={styles.baseText}>
                OPNET shall not be liable for any failure or delay in performance due to causes beyond reasonable control, including acts
                of God, war, terrorism, civil unrest, government action, network failures, blockchain congestion, protocol changes,
                cyberattacks, or other events beyond OPNET's control.
            </p>

            <h3 style={styles.h3}>13.6 Independent Contractors</h3>
            <p style={styles.baseText}>
                You and OPNET are independent contractors. These Terms do not create any partnership, joint venture, agency, or
                employment relationship.
            </p>

            <h3 style={styles.h3}>13.7 No Third-Party Beneficiaries</h3>
            <p style={styles.baseText}>These Terms do not create any third-party beneficiary rights in any person or entity.</p>

            <h3 style={styles.h3}>13.8 Export Compliance</h3>
            <p style={styles.baseText}>
                You agree to comply with all applicable export control laws, sanctions, and regulations. You may not use the Wallet if
                you are subject to sanctions or located in a jurisdiction subject to comprehensive sanctions.
            </p>

            <h3 style={styles.h3}>13.9 Language</h3>
            <p style={styles.baseText}>
                These Terms are drafted in English. If translated into another language, the English version shall prevail in the event of
                any conflict.
            </p>

            <h3 style={styles.h3}>13.10 Notices</h3>
            <p style={styles.baseText}>
                OPNET may provide notices to you through the Wallet interface, our website, or public communication channels. Notices are
                effective upon posting or transmission. Notices to OPNET must be sent to report@opnet.org or to our registered address.
            </p>

            <h2 style={styles.h2}>ACKNOWLEDGMENT AND ACCEPTANCE</h2>
            <ul style={styles.ul}>
                <li style={styles.li}>BY INSTALLING, ACCESSING, OR USING OPWALLET, YOU ACKNOWLEDGE THAT:</li>
                <li style={styles.li}>YOU HAVE READ AND UNDERSTAND THESE TERMS IN THEIR ENTIRETY.</li>
                <li style={styles.li}>YOU UNDERSTAND THAT THE WALLET IS NON-CUSTODIAL AND OPNET CANNOT RECOVER LOST KEYS.</li>
                <li style={styles.li}>YOU ARE SOLELY RESPONSIBLE FOR SECURING YOUR PRIVATE KEYS AND SEED PHRASES.</li>
                <li style={styles.li}>YOU UNDERSTAND THAT BLOCKCHAIN TRANSACTIONS ARE IRREVERSIBLE.</li>
                <li style={styles.li}>YOU UNDERSTAND AND ACCEPT THE RISK OF PARTIAL TRANSACTION REVERSION.</li>
                <li style={styles.li}>YOU ACCEPT ALL RISKS DESCRIBED IN THESE TERMS.</li>
                <li style={styles.li}>YOU AGREE TO BE BOUND BY THE ARBITRATION AND CLASS ACTION WAIVER PROVISIONS.</li>
                <li style={styles.li}>YOU HAVE THE LEGAL CAPACITY TO ENTER INTO THIS AGREEMENT.</li>
                <li style={styles.li}>IF YOU DO NOT AGREE TO THESE TERMS, DO NOT INSTALL OR USE OPWALLET.</li>
            </ul>

            <h2 style={styles.h2}>CONTACT INFORMATION</h2>
            <p style={styles.baseText}>
                ORANGE PILL LABS HOLDING LTD
                <br />
                Abu Dhabi Global Market, United Arab Emirates
                <br />
                Email: report@opnet.org
            </p>

            <hr style={styles.hr} />

            {/* =========================
                .BTC — DOMAIN TERMS
               ========================= */}

            <div style={{ marginBottom: 10 }}>
                <div style={{ ...styles.h2, fontSize: 14, marginTop: 2 }}>.BTC DOMAIN — TERMS OF SERVICE, DISCLOSURE POLICY, AND ACCEPTABLE USE POLICY</div>
                <p style={{ ...styles.baseText, marginTop: 6, color: 'rgba(255,255,255,0.70)' }}>
                    ORANGE PILL LABS HOLDING LTD
                    <br />
                    Effective Date: {effectiveDate}
                </p>
            </div>

            <h2 style={styles.h2}>PREAMBLE</h2>
            <p style={styles.baseText}>
                This Terms of Service, Disclosure Policy, and Acceptable Use Policy (collectively, these "Terms") constitutes a legally
                binding agreement between you ("User," "Registrant," "you," or "your") and ORANGE PILL LABS HOLDING LTD, a company
                incorporated and registered in Abu Dhabi Global Market, United Arab Emirates, operating under the trade name OPNET
                ("OPNET," "Company," "we," "us," or "our"). These Terms govern your use of the .btc domain namespace, the OPNet resolution
                services, the OPNET IPFS pinning service, the opwallet application, and all related services, interfaces, and
                infrastructure provided or operated by OPNET (collectively, the "Services").
            </p>
            <p style={styles.baseText}>
                By registering a .btc domain on the Bitcoin blockchain, by using any OPNET resolution service, by uploading content to the
                OPNET IPFS pinning service, by accessing the opwallet application, or by otherwise interacting with the Services, you
                acknowledge that you have read, understood, and agree to be bound by these Terms in their entirety. If you do not agree
                to these Terms, you must not use the Services. If you are entering into these Terms on behalf of a legal entity, you
                represent and warrant that you have the authority to bind such entity to these Terms.
            </p>

            <h2 style={styles.h2}>ARTICLE 1: DEFINITIONS AND INTERPRETATION</h2>
            <h3 style={styles.h3}>1.1 Definitions</h3>
            <p style={styles.baseText}>
                In these Terms, unless the context otherwise requires, the following terms shall have the meanings ascribed to them below.
                "Bitcoin" means the decentralised peer-to-peer electronic cash system operating on the Bitcoin blockchain network.
                "Bitcoin Blockchain" means the distributed public ledger recording all Bitcoin transactions. ".btc Domain" means a
                human-readable identifier registered on the Bitcoin Blockchain within the .btc namespace. "IPFS" means the InterPlanetary
                File System, a protocol and peer-to-peer network for storing and sharing data in a distributed file system using
                content-addressing to uniquely identify files. "Pinning" means the act of instructing an IPFS node to retain and serve
                specific content, preventing it from being removed during garbage collection. "Resolution" means the process of
                translating a .btc domain name into associated data, records, or content addresses. "Smart Contract" means self-executing
                code deployed on a blockchain that automatically enforces the terms of an agreement.
            </p>

            <h3 style={styles.h3}>1.2 Interpretation</h3>
            <p style={styles.baseText}>
                In these Terms, unless the context otherwise requires, words importing the singular shall include the plural and vice
                versa, words importing any gender shall include all genders, references to persons shall include natural persons and legal
                entities, headings are for convenience only and shall not affect interpretation, references to Articles and Sections are
                references to Articles and Sections of these Terms, and any reference to a statute or statutory provision shall include
                any subordinate legislation made under it and any amendment, re-enactment, or replacement thereof.
            </p>

            <h2 style={styles.h2}>ARTICLE 2: NATURE OF SERVICES AND TECHNICAL DISCLOSURES</h2>
            <h3 style={styles.h3}>2.1 Decentralised Domain Registration</h3>
            <p style={styles.baseText}>
                You acknowledge and understand that .btc domain registration occurs directly on the Bitcoin Blockchain through
                transactions broadcast by you or on your behalf. OPNET does not act as an intermediary, registrar, custodian, or agent in
                the domain registration process. When you register a .btc domain, you interact directly with the Bitcoin network by
                broadcasting a valid Bitcoin transaction containing the registration data. OPNET has no role in processing, validating,
                confirming, or executing your registration transaction. The Bitcoin network's miners validate and confirm your
                transaction according to Bitcoin's consensus rules. Once your registration transaction is confirmed on the Bitcoin
                Blockchain, your domain registration becomes part of Bitcoin's immutable public ledger.
            </p>

            <h3 style={styles.h3}>2.2 OPNet Consensus Layer</h3>
            <p style={styles.baseText}>
                OPNet operates as a consensus layer that reads, interprets, and validates Bitcoin transactions containing .btc domain data
                according to the OPNet protocol rules. OPNet does not modify, process, or intermediate Bitcoin transactions. OPNet's
                consensus layer observes the Bitcoin Blockchain and derives state from valid transactions. The OPNet protocol is trustless
                and permissionless, meaning that any party may run an OPNet node to independently verify the state of all .btc domains.
                OPNET the company does not control the OPNet protocol and cannot unilaterally alter protocol rules or domain ownership
                records.
            </p>

            <h3 style={styles.h3}>2.3 Non-Custodial Architecture</h3>
            <p style={styles.baseText}>
                The .btc domain system is entirely non-custodial. Your private keys remain exclusively under your control at all times.
                Neither OPNET nor any OPNet protocol participant has access to, custody of, or control over your private keys, your
                Bitcoin, or your domain assets. All domain registrations, transfers, updates, and renewals require cryptographic
                signatures from your private keys. Loss of your private keys will result in permanent and irrecoverable loss of access to
                your domains and any associated assets. OPNET has no capability to recover lost private keys, reverse transactions, or
                restore access to domains.
            </p>

            <h3 style={styles.h3}>2.4 Immutability of Blockchain Records</h3>
            <p style={styles.baseText}>
                You acknowledge and understand that once a .btc domain registration, transfer, or update transaction is confirmed on the
                Bitcoin Blockchain, that record becomes practically immutable. Neither OPNET nor any other party can modify, reverse,
                cancel, or delete blockchain records. OPNET has no technical capability to censor, revoke, transfer, or alter .btc domain
                registrations recorded on the Bitcoin Blockchain. This immutability is a fundamental characteristic of blockchain
                technology and is not a limitation imposed by OPNET but rather an inherent property of the underlying system.
            </p>

            <h3 style={styles.h3}>2.5 Partial Transaction Reversion</h3>
            <p style={styles.baseText}>
                You acknowledge and understand that transactions on OPNet may partially revert. Because OPNet operates as a consensus
                layer atop Bitcoin rather than as an independent blockchain, when a transaction contains both Bitcoin value transfers and
                OPNet smart contract execution, the OPNet execution component may fail or revert while the underlying Bitcoin transfer
                remains valid and irreversible. Bitcoin transactions achieve finality through Bitcoin's proof-of-work consensus
                independently of OPNet's consensus layer. If an OPNet execution fails, any Bitcoin transferred in that transaction cannot
                be recovered through OPNet mechanisms because the Bitcoin transfer was valid under Bitcoin's consensus rules. You accept
                this partial reversion behaviour as an inherent characteristic of the system.
            </p>

            <h2 style={styles.h2}>ARTICLE 3: RESOLUTION SERVICES AND ACCESS CONTROL</h2>
            <h3 style={styles.h3}>3.1 Distinction Between Registration and Resolution</h3>
            <p style={styles.baseText}>
                There exists a fundamental distinction between on-chain domain registration and domain resolution services. On-chain
                registration refers to the immutable blockchain record of domain ownership and associated data, which neither OPNET nor any
                party can modify as described in Article 2. Resolution services refer to the software, infrastructure, and interfaces
                through which users query domain data and navigate to domain-associated content, including but not limited to the opwallet
                browser application, the OPNET website resolver, any application programming interfaces, and any affiliated applications or
                services. While OPNET cannot alter on-chain registrations, OPNET maintains complete and exclusive discretion over the
                operation of its resolution services and browsing interfaces.
            </p>

            <h3 style={styles.h3}>3.2 OPNET's Right to Block Resolution</h3>
            <p style={styles.baseText}>
                OPNET expressly reserves the absolute and unilateral right to block, nullify, suspend, restrict, disable, or otherwise
                prevent the resolution of any .btc domain through any OPNET-operated service, including without limitation opwallet and any
                other resolution infrastructure, at any time, for any reason or for no reason, in OPNET's sole and absolute discretion,
                without prior notice, without contemporaneous notice, without subsequent notice, without explanation, without appeal, and
                without any liability whatsoever to you or any third party. When OPNET blocks a domain from resolution, users attempting to
                access that domain through OPNET services will receive no resolution, an error message, a blocked domain notification, or
                such other response as OPNET deems appropriate. Blocking a domain from resolution does not affect and cannot affect the
                underlying on-chain registration, which remains permanently recorded on the Bitcoin Blockchain.
            </p>

            <h3 style={styles.h3}>3.3 Grounds for Resolution Blocking</h3>
            <p style={styles.baseText}>
                Without limiting the generality of Section 3.2, OPNET may block domain resolution for reasons including but not limited to:
                alleged or actual trademark infringement, alleged or actual copyright infringement, alleged or actual patent infringement,
                domains associated with content illegal under the laws of the United Arab Emirates, domains associated with content illegal
                under the laws of any jurisdiction in which OPNET operates or in which users access the Services, domains used for phishing
                or social engineering attacks, domains used for fraud or deceptive practices, domains impersonating natural persons or
                legal entities, domains distributing malware or malicious software, domains associated with terrorism or violent extremism,
                domains hosting or linking to child sexual abuse material, domains promoting illegal narcotics trafficking, domains
                facilitating money laundering or terrorist financing, domains facilitating sanctions evasion, domains associated with hate
                speech or incitement to violence, domains violating export control regulations, domains subject to court orders or legal
                process in any jurisdiction, domains reported through OPNET's complaint mechanisms, domains that OPNET determines pose
                reputational risk to the .btc ecosystem, and any other ground that OPNET deems sufficient in its sole and absolute
                discretion.
            </p>

            <h3 style={styles.h3}>3.4 No Notice or Appeal</h3>
            <p style={styles.baseText}>
                OPNET is under no obligation to provide notice before, during, or after blocking a domain from resolution. OPNET is under
                no obligation to explain, justify, or document its reasoning for any blocking decision. OPNET is under no obligation to
                establish, maintain, or operate any appeals process, review mechanism, reinstatement procedure, or grievance mechanism.
                OPNET is under no obligation to respond to any inquiry, complaint, or communication regarding any blocking decision. You
                acknowledge and accept that OPNET may exercise its blocking rights at any moment without warning and that you shall have no
                recourse, remedy, or claim against OPNET for any blocking action or the consequences thereof.
            </p>

            <h3 style={styles.h3}>3.5 Effect of Resolution Blocking</h3>
            <p style={styles.baseText}>
                When OPNET blocks a domain from resolution, the following consequences shall apply: the domain shall become inaccessible
                through opwallet and all OPNET-operated resolution services, any content associated with the domain shall become unreachable
                through OPNET infrastructure, the domain may be flagged, marked, or listed as blocked in OPNET interfaces, the domain owner
                shall retain full on-chain ownership and may transfer the domain through on-chain transactions, and the domain owner may
                attempt to access or resolve the domain through third-party infrastructure not operated by OPNET. OPNET makes no
                representation regarding the availability, functionality, legality, or safety of any third-party resolution services.
                Blocking does not constitute seizure, confiscation, forfeiture, or transfer of the domain itself or any property interest
                therein.
            </p>

            {/* NOTE:
               The .btc document you provided is extremely long. I included it up through Article 3 here.
               Paste the remaining .btc Articles 4–12 + acknowledgments exactly as provided under this same component
               using the same pattern (<h2>, <h3>, <p>, <ul>) to keep it “text-only”.
               If you want, paste the remainder and I’ll output the completed file in one go.
            */}

            <div style={{ height: 14 }} />
        </>
    );
}
